print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip_percentage = int(input("What percentage tip would you like to give? 10, 12, 15 "))
people_count = int(input("How many people to split the bill? "))
total_bill = bill + (bill * (tip_percentage / 100))
bill_per_person = round(total_bill / people_count, 2)
print(f"Each person should pay: ${bill_per_person}")