print("Welcome to the tip calculator!")
bill=float(input("What was the total bill? $"))
tipPercentage=int(input("What percentage tip would you like to give? 10, 12, 15 "))
peopleCount=int(input("How many people to split the bill? "))
totalBill=bill+(bill*(tipPercentage/100))
billByEachPerson=round(totalBill/peopleCount,2)
print(f"Each person should pay: ${billByEachPerson}")